### ISSUE TITLE
这个程序是做什么的

### ISSUE THREAD

**Issue by yonh** [shirakun/conohaDNS#1]
这个程序是做什么的,管理DNS?,能不能给份中文文档

**Comment by shirakun** [comment]
通过conoha的api管理在conoha托管的域名dns解析
conoha自己的dns页面比较难用,尤其是解析记录很多的时候,没有任何排序,搜索功能
偶尔会出现保存失败导致所有的变动无法保存
多次找conoha反应这个问题,但未得到解决
于是做了一个管理面板

**Comment by yonh** [comment]
知道了
